basic/models/EvolucaoVendas.php
<?php

namespace app\models;

use Yii;
use DateTime;
use \app\components\My;

/**
 * This is the model class for table "evolucaovendas".
 *
 * @property integer $id
 * @property string $ISBN
 * @property string $data
 * @property integer $quantidade
 *
 * @property Publicacao $publicacao
 */
class EvolucaoVendas extends \yii\db\ActiveRecord
{
    public $titulo;
    
    public static function findWithPublicacao() {
        return parent::find()
                ->select(['e.id','e.ISBN','e.data','e.quantidade',
                        "titulo"=>"concat(p.titulo,' ',p.subtitulo)",
                        ])  
                ->from(['e'=>'evolucaovendas'])
                ->innerJoin(['p'=>'publicacao'],'p.isbn=e.isbn');
    }
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'evolucaovendas';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ISBN', 'data', 'quantidade'], 'required'],
            [['data'], 'safe'],
            [['data'], 'checkMinimalDate'],
            [['quantidade'], 'integer'],
            [['ISBN'], 'string', 'max' => 13],
            [['ISBN'], 'checkISBNExistense'],
            [['ISBN'], 'unique', 'targetAttribute' => ['ISBN', 'data'],
                'message' => Yii::t('app','A combinação dos campos ISBN ({isbn}) e data ({data}) já existem na tabela evolução de vendas',
                            ['isbn'=>$this->ISBN,'data'=>$this->data])]
        ];
    }

    public function checkISBNExistense($attribute, $params) {
        if(!isset($this->publicacao)) {
            $this->addError($attribute, Yii::t('app', 'ISBN não existe na tabela de publicações.'));
        }
    }
    
    public function checkMinimalDate($attribute, $params)
    {
        if(isset($this->publicacao) && 
           My::sqlData($this->$attribute)<My::sqlData($this->publicacao->dataEdicao)) {
            $this->addError($attribute, Yii::t('app', 'A data de venda é menor que a data de edição.'));
        }
    }
    
    
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'ISBN' => Yii::t('app', 'Isbn'),
            'data' => Yii::t('app', 'Data'),
            'sqlData' => Yii::t('app', 'Data'),
            'quantidade' => Yii::t('app', 'Quantidade'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPublicacao()
    {
        return $this->hasOne(Publicacao::className(), ['ISBN' => 'ISBN']);
    }

    public function beforeValidate() {
        $this->data=My::sqlData($this->data);        
        return parent::beforeValidate();
    }
    
    public function beforeSave($insert) {        
        $this->data=My::sqlData($this->data);        
        return parent::beforeSave($insert);
    }
    
    public function afterValidate() {
        $this->data=My::phpData($this->data);
        return parent::afterValidate();
    }

    public function afterFind() {                
        $this->data=My::phpData($this->data);
        return parent::afterFind();
    }
    
   
}

basic/controllers/EvolucaovendasController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Publicacao;
use app\models\EvolucaoVendas;
use app\models\EvolucaoVendasSearch;
use app\models\EvolucaoVendasImporta;
use app\components\MyController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use alexgx\phpexcel;
use PHPExcel_IOFactory;
use app\components\MyExcel;
use yii\helpers\Json;
use yii\web\HttpException;
use \yii\grid\GridView;
use \yii\data\ArrayDataProvider;

/**
 * EvolucaoVendasController implements the CRUD actions for EvolucaoVendas model.
 */
class EvolucaovendasController extends MyController
{
    public $uploadFolder;
    
    public function init() {
        $this->uploadFolder = Yii::getAlias('@app') . "\upload_vendas\\";
        parent::init();
    }
        
    private function saveFile($model){
        if ($model->load(Yii::$app->request->post())){
            $file = UploadedFile::getInstance($model, 'ficheiro');              
            if($file!=null) {            
                $date = date_create($model->dataImportacao);
                $model->ficheiro='Vendas_'.date_format($date,"Y-m-d").'.'.$file->extension;                
            }
            $path=$this->uploadFolder . $model->ficheiro;
            $file->saveAs($path,true);                                                                
            return true;            
        }
        return false;
    }
    
    public function actionImport() {
        $p = Yii::$app->request->post();
        $ficheiro = $p['file'];
        $data = $p['date'];
        $selection = $p['selection'];
        foreach($selection as $i=>$v) $selection[$i]= Json::decode($v);
        
        $transaction = Yii::$app->db->beginTransaction();
        try {            
            $result=[];
            foreach ($selection as $v) {
                $reg = new EvolucaoVendas();
                $reg->ISBN = $v['isbn'];
                $reg->quantidade = intval($v['quantidade']);
                $reg->data       = $data;                
                if($reg->validate()){                    
                    $reg->save();                   
                    $result[]=
                        array_merge(
                                $reg->toArray(),
                                ['message'=>'ok']
                        );
                }else {
                    $err= [];
                    foreach($reg->errors as $field=>$message){
                        $err['campo']=$field;
                        $err['mensagem']=$message[0];
                    }
                    $result[] = array_merge(
                                $reg->toArray(),
                                ['message'=>[$err]]
                        );
                }
            }            
            $transaction->commit();
            return $this->render('import', [
                'file'        => $ficheiro,
                'data'        => $data,
                'result'      => $result,                                             
                'columns'     => 
                       ['ISBN',
                        'data',
                        [
                            'attribute'=>'quantidade',            
                            'hAlign'=>'right',
                        ],                           
                        [                            
                            'attribute' => 'resultado',
                            'format' => 'raw',
                            'contentOptions'=>['style'=>'width:40%;'],
                            'value' => function ($model) {                      
                                            if($model['message']=='ok'){
                                                return '<div>'.$model['message'].'</div>';
                                            }else{
                                                return GridView::widget([
                                                            'layout'=>"{items}",                                                            
                                                            'showHeader' => false, 
                                                            'tableOptions'=>['class'=>'table table-bordered',
                                                                    'style'=>'background-color:transparent'],
                                                            'dataProvider' => new ArrayDataProvider([
                                                                                        'allModels' => $model['message'],                                    
                                                                            ]),                            
                                                            'columns' => [
                                                                [
                                                                    'attribute'=>'campo',
                                                                    'contentOptions'=>['style'=>'border-color: transparent;'],
                                                                ],
                                                                [
                                                                    'attribute'=>'mensagem',
                                                                    'contentOptions'=>['style'=>'border-color: transparent;'],
                                                                ]
                                                                ],

                                                        ]);
                                            };
                                    },

                        ]]
            ]);
        } catch (Exception $e) {            
            $transaction->rollBack();
            throw EvolucaoVendasImportException($e->getMessage());
        }
        
    }
    
    /**
     * Importa relatorio mensal de vendas de Publicação.
     * @return mixed
     */
    public function actionUpload()
    {
        $model = new EvolucaoVendasImporta();
        
        if( $this->saveFile($model))
            return $this->redirect(['confirmation', 
                            'data'      => $model->dataImportacao,
                            'file'      => $model->ficheiro]);
        else
            return $this->render('upload', [
                'model'     => $model,             
            ]);
    }
    
    public function actionConfirmation($data,$file)
    {
        $this->getView()->registerJsFile("/js/color.js");
        $path=$this->uploadFolder . $file;        
                  $a=isset($record['isbn']);
  
        $ex = new MyExcel();
        $ex->readSpreadsheetData($path);        

        $arr=$ex->export2Array( new \app\components\MyExcelImportModel('importacaoVendas.json') );
        foreach($arr as $recno=>$record){
            $model =Publicacao::findOne(['isbn'=>$record['isbn']]);
            $arr[$recno]['valid'] = 
                    isset($record['isbn']) && (Publicacao::findOne(['isbn'=>$record['isbn']]) !== null) ;            
        }
        
        return $this->render('import_confirmation', [
            'array'     => $arr, 
            'columns'   => array_merge([
                            [
                                'class' => 'yii\grid\CheckboxColumn',
                                'checkboxOptions' => function($model, $key, $index, $column) {
                                      return $model['valid'] 
                                              ? ['checked' =>'true',
                                                'value'=>Json::encode([
                                                                'isbn'=>$model['isbn'].'',
                                                                'quantidade'=>$model['quantidade']])] 
                                              : ['disabled'=>'' ,
                                                'value'=>Json::encode([
                                                                'isbn'=>$model['isbn'].'',
                                                                'quantidade'=>$model['quantidade']])];
                                }

                            ]
                        ], $ex->getModel()->columns),
            'file'      => $file,
            'data'      => $data,
        ]);
    }

    /**
     * Lists all EvolucaoVendas models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new EvolucaoVendasSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single EvolucaoVendas model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new EvolucaoVendas model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new EvolucaoVendas();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing EvolucaoVendas model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

basic/views/evolucaoVendas/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\EvolucaoVendas */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="evolucao-vendas-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'ISBN')->textInput(['maxlength' => 13]) ?>

    <?= $form->field($model, 'data')->textInput() ?>

    <?= $form->field($model, 'quantidade')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

basic/views/evolucaoVendas/_form_upload.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\EvolucaoVendasImporta */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="publicacao-autor-form">

    <?php $form = ActiveForm::begin([
        'id' => 'WvendasImporta',
        'options' => ['enctype' => 'multipart/form-data'],
        'validationUrl' => ['/publicacaoautor/validate'],
/*        'enableClientScript' => true,
        'enableClientValidation' => true,
        'enableAjaxValidation' => true,*/
    ]); ?>
    
    <?= $form->field($model, 'dataImportacao')->widget(\yii\jui\DatePicker::classname(), [
        'options'       => ['class' => 'form-control'],
        'language' => 'pt',
        'dateFormat' => 'dd-MM-yyyy',        
    ]) ?>

    <?= $form->field($model, 'ficheiro')->fileInput(['maxlength' => 255]) ?>   

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Importa'), ['btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
    <div id="ajaxWait" style="display:none;">
        <img src="/img/ajax loader.gif">
    </div>
</div>

<?php
$script = <<<EOD
$("form").submit( function(event) {        
        $("#ajaxWait").show("slow");
});    
EOD;
$this->registerJs($script);        
?>

basic/views/evolucaoVendas/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\EvolucaoVendasSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="evolucao-vendas-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'ISBN') ?>

    <?= $form->field($model, 'data') ?>

    <?= $form->field($model, 'quantidade') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

basic/views/evolucaoVendas/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\EvolucaoVendas */

$this->title = Yii::t('app', 'Create Evolucao Vendas');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Evolucao Vendas'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="evolucao-vendas-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

basic/views/evolucaoVendas/import.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\data\ArrayDataProvider;
use yii\helpers\BaseInflector;

/* @var $this yii\web\View */
/* @var $result array */
/* @var $columns array */
/* @var $file string */
/* @var $data string */


$this->title = Yii::t('app', 'Importação Evolucao Vendas');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="evolucao-vendas-index">

    <h1><?= Html::encode($this->title) ?></h1>    
                
    <?php
        $cols = array_merge([['class' => 'yii\grid\SerialColumn']],$columns );
        echo GridView::widget([
                    'dataProvider' => new ArrayDataProvider([
                                                'allModels' => $result,    
                                                'pagination' => [
                                                    'pageSize' => 9999,
                                                ]                                   
                                    ]), 
                    'resizableColumns'=>true,
                    'persistResize'=>true,
                    'columns' => $columns,

                ]); 
        echo Html::endForm();
        ?>
    
</div>

<?php
$script = <<<EOD
$.each($('.importRecno').find('input[type=checkbox][disabled]').closest('.importRecno').find('td'),function( idx, me ){
        var bgCor = getBgColorHex($(me).css("color"));
        var newBgCor=LightenDarkenColor(bgCor, 60);
        $(me).css("color",newBgCor);        
});

EOD;
$this->registerJs($script);
?>

basic/views/evolucaoVendas/import_confirmation.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\data\ArrayDataProvider;
use yii\helpers\BaseInflector;

/* @var $this yii\web\View */
/* @var $array array */
/* @var $columns array */
/* @var $file string */
/* @var $data string */


$this->title = Yii::t('app', 'Confirmação Evolucao Vendas');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="evolucao-vendas-index">

    <h1><?= Html::encode($this->title) ?></h1>    
           
    <?=Html::beginForm('/evolucaovendas/import','post');?>
        <p>
    <?=Html::submitInput( Yii::t('app', 'Importa {ficheiro}',['ficheiro'=>  BaseInflector::titleize($file)]), ['class' => 'btn btn-success']) ?>            
        </p>
    <?=Html::hiddenInput('file', $file);?>
    <?=Html::hiddenInput('date', $data);?>
    <?php
        $cols = array_merge([['class' => 'yii\grid\SerialColumn']],$columns );
        echo GridView::widget([
                    'dataProvider' => new ArrayDataProvider([
                                                'allModels' => $array,    
                                                'pagination' => [
                                                    'pageSize' => 9999,
                                                ]
                    ]),        
                    'resizableColumns'=>true,    
                    'persistResize'=>true,
                    'rowOptions'   => function ($model, $index, $widget, $grid) {
                                        return ['class'=>'importRecno'];
                        },

                    'columns' => $cols,

                ]); 
        echo Html::endForm();
        ?>
    <div id="ajaxWait" style="display:none;">
        <img src="/img/ajax loader.gif">
    </div>
</div>

<?php
$script = <<<EOD
$("form").submit( function(event) {        
        $("#ajaxWait").show("slow");
});            
$.each($('.importRecno').find('input[type=checkbox][disabled]').closest('.importRecno').find('td'),function( idx, me ){
        var bgCor = getBgColorHex($(me).css("color"));
        var newBgCor=LightenDarkenColor(bgCor, 60);
        $(me).css("color",newBgCor);        
});
        
$("input[type=submit]").attr("disabled", $('input[name="selection[]"]:not(:disabled)').length==0 ? "" : undefined );           

EOD;
$this->registerJs($script);
?>

basic/views/evolucaoVendas/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use app\models\EvolucaoVendas;
use app\models\Publicacao;
use yii\jui\AutoComplete;
use yii\helpers\ArrayHelper;
use yii\web\JsExpression;
use yii\db\Query;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\EvolucaoVendasSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Evolucao Vendas');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="evolucao-vendas-index">
    <?php         
        $distinctISBN = EvolucaoVendas::find()
                        ->select(['value'=>'publicacao.ISBN', 'label'=>"concat(publicacao.isbn,' - ',publicacao.titulo)",'ISBN'=>'publicacao.ISBN','id'=>'publicacao.ISBN'])
                        ->innerJoin('publicacao','publicacao.isbn=evolucaovendas.isbn')
                        ->distinct()
                        ->asArray()
                        ->all();?>    
    <?php $distinctData = EvolucaoVendas::find()
                        ->select(['value'=>'data', 'value'=>'data'])
                        ->distinct()        
                        ->asArray()
                        ->all();?>
    <?php Pjax::begin(); echo GridView::widget([        
        'id' => 'grid-evolucaovendas',
        'resizableColumns'=>true,
        'persistResize'=>true,
        'responsive'=>true,
        'hover'=>true,
        'condensed'=>true,               
        'panel' => [
            'heading'=>'<h3 class="panel-title"><i class="glyphicon glyphicon-th-list"></i> '.Html::encode($this->title).' </h3>',
            'type'=>'info',
            'before'=>Html::a('<i class="glyphicon glyphicon-plus"></i> '.Yii::t('app', 'Importar Vendas'), ['upload'], ['class' => 'btn btn-success']).' '.
                      Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['index'], ['class' => 'btn btn-info']),
            'after' =>false,
        ],
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
//            ['class' => 'yii\grid\SerialColumn'],        
            [
                'attribute'=>'ISBN',
                'filter' => AutoComplete::widget([
                        'model' => $searchModel,
                        'attribute' => 'ISBN',                        
                        'options' => [ 
                            'class' => 'form-control',
                        ],
                        'clientOptions' => [
                            'source' => $distinctISBN,
                            'autoFill'=>true,
                            'minLength' =>0,
                            'select' => new JsExpression("function( event, ui ) {
                                $('evolucaovendassearch-ISBN').val(ui.item.id);
                            }"),
                        ],                                               
                    ]),
                
            ],
            [
                'attribute' => 'titulo',
                'format' => 'raw',
                'value' => function($model){
                    return $model->publicacao->descricaoHTML;
                }
            ],
            [
                'attribute'=>'data',
                'filter' => AutoComplete::widget([
                        'model' => $searchModel,
                        'attribute' => 'data',                        
                        'options' => [ 
                            'class' => 'form-control',
                        ],
                        'clientOptions' => [
                            'source' => $distinctData,
                            'autoFill'=>true,
                            'minLength' =>0,
                            'select' => new JsExpression("function( event, ui ) {
                                $('evolucaovendassearch-data').val(ui.item.id);
                            }"),
                        ],

                    ]),                
                
            ],
            [
                'attribute'=>'quantidade',            
                'hAlign'=>'right',
            ],
            ['class' => '\kartik\grid\ActionColumn',
                'hiddenFromExport'=>true,
                'template'=>'{delete}'
            ],        
        ],
    ]); Pjax::end(); ?>
            
</div>

basic/views/evolucaoVendas/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\EvolucaoVendas */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Evolucao Vendas',
]) . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Evolucao Vendas'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="evolucao-vendas-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

basic/views/evolucaoVendas/upload.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\EvolucaoVendas */

$this->title = Yii::t('app', 'Upload Evolucao Vendas');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Evolucao Vendas'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="evolucao-vendas-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form_upload', [
        'model' => $model,
    ]) ?>

</div>

basic/views/evolucaoVendas/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\EvolucaoVendas */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Evolucao Vendas'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="evolucao-vendas-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'ISBN',
            'data',
            'quantidade',
        ],
    ]) ?>

</div>