basic/models/Recibo.php
<?php

namespace app\models;

use Yii;
use \app\components\My;
use \yii\db\Query;


/**
 * This is the model class for table "recibo".
 *
 * @property integer $id
 * @property integer $idAutor
 * @property string $data
 *
 * @property Autor $autor
 * @property Recibopublicacao[] $recibopublicacoes
 * @property RecVendasComissao[] $detalhes
 */
class Recibo extends \yii\db\ActiveRecord
{
    public $nome,$valor;
    
    
    public static function find() {
        return parent::find();                
    }
    
    public static function findWithAutor() {
        $ret= parent::find()
                ->select(['r.id', 'r.idAutor', 'r.data', 
                        "nome"=>"concat(a.primeiroNome,' ',a.nomeDoMeio,' ',a.apelido)",                     
                        'valor'=>"sum(ifnull(rp.valor,0))"])  
                ->from(['r'=>'recibo'])
                ->innerJoin(['a'=>'autor'],'a.id=r.idAutor')
                ->leftJoin(['rp'=>'recibopublicacao'],'rp.idRecibo=r.id AND rp.valor<>0')
                ->groupBy(['r.id', 'r.idAutor', 'r.data', 
                            'a.primeiroNome','a.nomeDoMeio','a.apelido']);
    //    $a=$ret->createCommand()->getRawSql();
        return $ret;
    }
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'recibo';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['idAutor', 'data'], 'required'],
            [['idAutor'], 'integer'],
            [['data'], 'safe'],            
            [['data'], 'checkDate'],
        ];
    }
    
    public function checkDate($attribute, $params)
    {        
        
        if($this->data!='') {
            $id = (empty($this->id)) ? 999999999999999 : $this->id;
            $data = My::sqlData($this->data);        
            if( ($model=Recibo::find()->where("idAutor=$this->idAutor AND id <> $id AND data ='$data'")->one()) != null ) {
                $this->addError($attribute,Yii::t('app','Existe outro recibo ({recibo}) na data definida',['recibo'=>'id='.$model->id]));
            }
            if( ($model=Recibo::find()->where("idAutor=$this->idAutor AND id < $id AND data > '$data'")->one()) != null ) {
                $this->addError($attribute, Yii::t('app', 'Existe um recibo ({recibo}) anterior com data superior á definida.',['recibo'=>'id='.$model->id]));
            }
            if( ($model=Recibo::find()->where("idAutor=$this->idAutor AND id > $id AND data < '$data'")->one()) != null ) {
                $this->addError($attribute, Yii::t('app', 'Existe um recibo ({recibo}) posterior data inferior á definida.',['recibo'=>'id='.$model->id]));           
            }
        }
    }
    
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'idAutor' => Yii::t('app', 'Id Autor'),
            'data' => Yii::t('app', 'Data'),
            'nome' => Yii::t('app', 'Nome'),
            'valor' => Yii::t('app', 'Valor')
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAutor()
    {
        return $this->hasOne(Autor::className(), ['id' => 'idAutor']);
    }

    /**
     * @return \yii\db\ActiveRecord
     */
    public function getRecibopublicacoes()
    {
        return $this->hasMany(Recibopublicacao::className(), ['idRecibo' => 'id']);
    }
    
    public function beforeValidate() {
        $this->data=My::sqlData($this->data);        
        return parent::beforeValidate();
    }
    
    public function beforeSave($insert) {        
        $this->data=My::sqlData($this->data);        
        return parent::beforeSave($insert);
    }
    
    public function afterValidate() {
        $this->data=My::phpData($this->data);
        return parent::afterValidate();
    }

    public function afterFind() {                
        $this->data=My::phpData($this->data);
        return parent::afterFind();
    }        
    
    /**
     * 
     * @return \yii\db\ActiveRecord
     */
    public function getVendasEComissoes() {        
        $query = (new \yii\db\Query());
        $query=$query
            ->select(['c.idAutor','c.tipoAutoria', 'c.idPublicacao','c.ISBN','c.comissao',
                        'data'=>'max(c.data)',
                        'totalVendas'=>'max(c.totalVendas)',
                        'qtVendas'=>'max(c.qtVendas)',
                        'comissaoVendas'=>'max(c.comissaoVendas)'])
            ->from('publicacaoautorvendascomissao c')            
            ->where(['c.idAutor' => $this->idAutor])
            ->andWhere(['<=','c.data',  My::sqlData($this->data)])
            ->groupBy(['c.tipoAutoria', 'c.idPublicacao','c.ISBN','c.comissao']);
        return $query;
    }
    
    /**
     * 
     * @return \yii\db\ActiveRecord
     */
    public function getPagamentos(){
        $query = (new \yii\db\Query());
        $query=$query
            ->select(['rp.idAutor', 'rp.tipoAutoria', 'rp.idPublicacao',
                        'data'=>'max(r.data)',
                        'sum(rp.valor) as valor',
                        ])
            ->from('recibopublicacao rp')            
            ->innerJoin('recibo r','r.id = rp.idRecibo')
            ->where(['rp.idAutor' => $this->idAutor])
            ->andWhere(['<','r.data',  My::sqlData($this->data)])
            ->groupBy(['rp.idAutor', 'rp.tipoAutoria', 'rp.idPublicacao']);
        return $query;
    }
    
    
    public function getPublicacoes(){
        $query = (new \yii\db\Query());
        $query=$query
            ->select(['pa.idAutor', 'pa.tipoAutoria', 'pa.idPublicacao','pa.comissao',
                        'dp.tiragem',
                        'valorTotal'=>'(dp.tiragem*p.pVenda)',
                        'comissaoTotal'=>'(if(dp.tiragem*p.pVenda*pa.comissao=0,0,dp.tiragem*p.pVenda*pa.comissao/100))'
                        ])
            ->from(['pa'=>'publicacaoautor']) 
            ->innerJoin(['p'=>'publicacao'],'p.id = pa.idPublicacao')
            ->innerJoin(['dp'=>'dadosproducaolivro'],'dp.id = pa.idPublicacao')
            ->where(['idAutor' => $this->idAutor])
            ;
        return $query;
    }
    /**
     * 
     * @return \yii\db\ActiveRecord
     */
    public function getRecibo(){
        $query = (new \yii\db\Query());
        $query=$query
            ->select(['rp.idAutor', 'rp.tipoAutoria', 'rp.idPublicacao',
                        'r.data',
                        'rp.valor',
                        ])
            ->from('recibopublicacao rp')            
            ->innerJoin('recibo r','r.id = rp.idRecibo')
            ->where(['rp.idRecibo' => $this->id])
            ;
        return $query;
    }
    
    /**
     * @return PublicacaoAutorVendasComissao
     */
    public function getDetalhes() {
        return ReciboPublicacao::getAutorRecibo($this->idAutor, $this->data);     
    }
            

}

basic/controllers/ReciboController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Recibo;
use app\models\ReciboSearch;
use app\components\MyController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\widgets\ActiveForm;
use yii\web\Response;

/**
 * ReciboController implements the CRUD actions for Recibo model.
 */
class ReciboController extends MyController
{
    
    public function beforeAction($action) {
        return parent::beforeAction($action);
    }
        
    /**
     * Lists all Recibo models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ReciboSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Recibo model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Recibo model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Recibo();

        if ($model->load(Yii::$app->request->post())){
            if( Yii::$app->request->isAjax ){                         
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model); 
            }else {
                $model->save();
                return $this->redirect(['update', 'id' => $model->id]);
            } 
        }
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Recibo model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);        

        if( Yii::$app->request->isPost ){            
            if(($valor = Yii::$app->request->post('ReciboPublicacao'))!=null) {
                if( Yii::$app->request->isAjax ){
                    $porLiquidar = $valor['porLiquidar'];unset($valor['porLiquidar']);
                    reset($valor);$valor = current($valor);
                    $valor = $valor['pagamento'];
                    
                    // end get valor pagamento
                    // get chave primaria do regisro adicionado ou alterado
                    $key=Yii::$app->request->post('editableKey');
                    $key= unserialize($key); unset($key['data']);
                    // Procura chave primaria
                    $rp= \app\models\ReciboPublicacao::findOne($key);
                    if($rp==null){   // se não existe - adiciona
                        $rp = new \app\models\ReciboPublicacao();
                        $rp->setAttributes($key);
                    }
                    $rp->pagamento=$valor;   //  Atribui valor pago
                    $rp->porLiquidar=$porLiquidar;
                    //
                    ActiveForm::validate($rp); 
                    if (! $rp->hasErrors()) {
                        $rp->save ();
                    }                
                    Yii::$app->response->format = Response::FORMAT_JSON;                  
                    $a=$rp->getErrors();
                    return $rp->hasErrors() 
                                ? [ 'message'=>isset($a['pagamento'][0]) ? $a['pagamento'][0] : 'Erro' ]
                                : ['output'=>  \Yii::$app->formatter->asCurrency($valor), 'message'=>''];
                }
            }elseif(Yii::$app->request->post('Recibo')!=null){
                $model->load(Yii::$app->request->post());
                if( Yii::$app->request->isAjax ){                         
                    Yii::$app->response->format = Response::FORMAT_JSON;
                    return ActiveForm::validate($model); 
                }else 
                    $model->save();
            }        
        }        
        return $this->render('update', [
            'model' => $model,
        ]);
    }
    
    

    /**
     * Detalhes of an existing Recibo model.     
     * @param integer $id
     * @return mixed
     */
    public function actionDetalhes($id)
    {
       /* $id=Yii::$app->request->post('expandRowKey');
        $id=$id!='' ? $id : Yii::$app->request->getQueryParam('expandRowKey');*/
        
        $model = $this->findModel($id);
        
        return $this->render('detalhes', [            
            'detalhes'=>$model->getDetalhes(), 
        ]);

    }
    
    
    /**
     * Deletes an existing Recibo model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $data = \app\components\My::sqlData($model->data);
        $exist = Recibo::find()->where(["idAutor"=>$model->idAutor])
                        ->andWhere("data>'$data'")->one();
        if( $exist != null ) {
            throw new ReciboInvalidoException(Yii::t('app','Só pode apagar o ultimo recibo de cada Autor/Coordenador.'));
        }else{
            \app\models\ReciboPublicacao::deleteAll("idRecibo=$id");
            $model->delete();        
            return $this->redirect(['index']);
        }
    }

    /**
     * Finds the Recibo model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Recibo the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Recibo::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}


class ReciboInvalidoException extends \yii\base\UserException
{
    /**
     * @return string the user-friendly name of this exception
     */
    public function getName()
    {
        return 'Não pode apagar recibo';
    }
}

basic/views/recibo/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\grid\GridView;
use \yii\data\ActiveDataProvider;
use \kartik\detail\DetailView;
use app\components\My;
use yii\widgets\Pjax;


/* @var $this yii\web\View */
/* @var $model app\models\Recibo */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="recibo-form">

    <?php $form = ActiveForm::begin([
        'id' => 'formRecibo',
     
     //   'validationUrl' => ['/publicacaoautor/validate'],//,'idPublicacao'=>$model->id],
        'enableClientScript' => true,
        'enableClientValidation' => true,
        'enableAjaxValidation' => true,
    ]); ?>

    <?= $form->field($model, 'idAutor')->widget(\app\components\MyAutoComplete::classname(), 
        [               
            'ajaxUrl'       => '/autor/autocomplete' ,
            'options'       => ['class' => 'form-control',
                                'readonly' => ! $model->isNewRecord,],            
            'clientOptions' => [
                'name'  => 'PublicacaoAutor[idAutor]',
                'value' => $model->idAutor,
                ]
            ]) ?>
    
    <?= $form->field($model, 'data')->widget(\yii\jui\DatePicker::classname(), [
        'options'       => ['class' => 'form-control'],
        'language' => 'pt',
        'dateFormat' => 'dd-MM-yyyy',        
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>
    
    <?php 
    $detalhes = $model->getDetalhes();
    $dataProvider = new activeDataProvider([
            'query' => $detalhes,
            'pagination' => [
                'pageSize' => 9999,
            ],
        ]); 
    if( $detalhes!=null ) { 
    ?>   
    <?php Pjax::begin(); echo GridView::widget([        
        'id' => 'grid-editRecibo',
        'resizableColumns'=>true,
        'persistResize'=>true,
        'responsive'=>true,
        'hover'=>true,
        'condensed'=>true,               
        'panel' => [
            'heading'=>'<h3 class="panel-title">'.
                            Html::a('<i class="glyphicon glyphicon-repeat"></i>  ', ['recibo/update','id'=>$model->id]).
                            '<i class="glyphicon glyphicon-th-list"></i> '.Html::encode($this->title).
                        ' </h3>',            
            'type'=>'info',
            'before'=>false,
            'after'=>false,
            'footer'=>false,
        ],
        
        'dataProvider' => $dataProvider,
        'showFooter'=>TRUE,
        'footerRowOptions'=>['style'=>'border-top-style: ridge;font-weight:bold;background-color:#FFFFCC;'],

        'columns' => [
//            [   'class' => 'kartik\grid\SerialColumn'],            
            [   'class' => '\kartik\grid\ExpandRowColumn',                
                    'expandTitle'=>Yii::t('app','Expande'),
                'collapseTitle'=>Yii::t('app','Colapsa'),
                'collapseAllTitle' => Yii::t('app','Colapsa todos'),
                'expandAllTitle' => Yii::t('app','Expande todos'),                
                'expandIcon'=>'<span class="glyphicon glyphicon-plus-sign"></span>',
                'collapseIcon'=>'<span class="glyphicon glyphicon-minus-sign"></span>',
                    'value' => function ($model, $key, $index, $column) {
                                    return GridView::ROW_COLLAPSED;
                    },
                    'detail' => function ($model, $key, $index, $column) {
                            return DetailView::widget([
                                    'model' => $model,
                                    'attributes' => [                                                                                                              
                                        [
                                            'group'=>true,
                                            'label'=>Yii::t('app','Autoria'),
                                            'rowOptions'=>['class'=>'info'],
                                        ],                                                    
                                        [
                                            'label' => Yii::t('app','Comissao '.$model->tipoAutoria),
                                            'value'=>$model->comissao,
                                        ],                                                                              
                                        [
                                            'label' => Yii::t('app','Comissao '.$model->tipoAutoria.' Total'),
                                            'value'=>  Yii::$app->formatter->asCurrency($model->comissaoTotal),
                                        ],                                                                                                                          
                                        [
                                            'group'=>true,
                                            'label'=>Yii::t('app','Publicacao'),
                                            'rowOptions'=>['class'=>'info'],                                            
                                        ],

                                        'tiragem',
                                        [
                                            'label' => Yii::t('app','P Venda'),
                                            'value'=>Yii::$app->formatter->asCurrency($model->publicacao->pVenda),
                                        ],                                            
                                        [
                                            'label' => Yii::t('app','Valor Total'),
                                            'value'=>Yii::$app->formatter->asCurrency($model->valorTotal),
                                        ],                                            
                                        [
                                            'group'=>true,
                                            'label'=>Yii::t('app','Vendas'),
                                            'rowOptions'=>['class'=>'info'],
                                            //'groupOptions'=>['class'=>'text-center']
                                        ],                                                    
                                        [
                                            'label' => Yii::t('app','Data'),
                                            'value'=>  My::sqlData($model->dataVenda),
                                        ],                               
                                        [
                                            'label' => Yii::t('app','Total'),
                                            'value'=>Yii::$app->formatter->asCurrency($model->totalVendas),
                                        ],                                  
                                        [
                                            'label' => Yii::t('app','Quantidade'),
                                            'value'=>$model->qtVendas,
                                        ],                           
                                        [
                                            'label' => Yii::t('app','Comissao '.$model->tipoAutoria),
                                            'value'=>Yii::$app->formatter->asCurrency($model->comissaoVendas),
                                        ],                                                                      
                                        [
                                            'group'=>true,
                                            'label'=>Yii::t('app','Pagamento'),
                                            'rowOptions'=>['class'=>'info'],
                                            //'groupOptions'=>['class'=>'text-center']
                                        ],                                                    
                                        [
                                            'label' => Yii::t('app','Data'),
                                            'value'=>My::sqlData($model->dataPagamento),
                                        ],                               
                                        [
                                            'label' => Yii::t('app','Pago'),
                                            'value'=>Yii::$app->formatter->asCurrency($model->pagamentosAnteriores),
                                        ],                                  
                                        [
                                            'label' => Yii::t('app','Divida'),
                                            'value'=>Yii::$app->formatter->asCurrency($model->comissaoVendas-$model->pagamentosAnteriores),
                                        ],                           
                                        [
                                            'label' => Yii::t('app','Por Liquidar'),
                                            'value'=>Yii::$app->formatter->asCurrency($model->comissaoTotal-$model->pagamentosAnteriores),
                                        ],                                                                                                                          
                                    ]                                    
                                ]);
                },


                'detailRowCssClass' => GridView::TYPE_DEFAULT,
                'pageSummary' => false,
            ],  
            'tipoAutoria',
            [
                'footer'=>Yii::t('app','Total'),            
                'format' => 'raw',
                'label' => Yii::t('app','Publicacao'),
                'value' => function ($model, $key, $index, $column) {
                                return $model->publicacao->ISBN.'<br>'.
                                    $model->publicacao->descricaoHTML;
                },
            ],                   
            [
                'label' => Yii::t('app','Divida'),
                'hAlign'=>'right', 
                'vAlign'=>'middle',                                        
                'value'=>function ($model, $key, $index, $column) {
                                return Yii::$app->formatter->asCurrency($model->comissaoVendas-$model->pagamentosAnteriores);
                },
                'footer'=> Yii::$app->formatter->asCurrency(
                            app\components\My::pageTotal($dataProvider->models,'comissaoVendas') -
                            app\components\My::pageTotal($dataProvider->models,'pagamentosAnteriores')),                                
            ], 
            [
                'class' => 'kartik\grid\EditableColumn',                    

                'attribute' => 'pagamento',                                        
                'value'     => function ($model) {                      
                    return Yii::$app->formatter->asCurrency($model->pagamento);
                },
                'readonly'=>function($model, $key, $index, $widget) {
                    return false;
                },
                'hAlign'=>'right', 
                'vAlign'=>'middle',                                        
                'footer'=> Yii::$app->formatter->asCurrency(app\components\My::pageTotal($dataProvider->models,'pagamento')),                
                'editableOptions' => function ($model, $key, $index) {
                    return [                                                         
                        'asPopover' => true,
                        'header'=>'Pagamento',
                        'placement'=>  kartik\popover\PopoverX::ALIGN_TOP_RIGHT ,
                        'type'      => kartik\popover\PopoverX::TYPE_PRIMARY,                        
                        'afterInput'=> function ($form, $widget) {
                                /* @var $form yii\widgets\ActiveForm */
                                echo $form->field($widget->model, 'porLiquidar',['template'=>'{input}',])->hiddenInput();
                        },
                        'submitButton'=> ['label'=>Yii::t('app','Enviar'),
                                        'icon'=>'<i class="ui-icon ui-icon-arrowthickstop-1-s"></i>'],
                        'resetButton'=> ['label'=>Yii::t('app','Voltar'),
                                        'icon'=>'<i class="ui-icon ui-icon-arrowreturnthick-1-w"></i>'],                        
                    ];
                },
            ],

        ],
    ]); 
}?>
    
</div>

basic/views/recibo/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modelsReciboSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="recibo-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'idAutor') ?>

    <?= $form->field($model, 'data') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

basic/views/recibo/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Recibo */

$this->title = Yii::t('app', 'Create Recibo');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Recibos'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="recibo-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

basic/views/recibo/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use \yii\helpers\Url;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\modelsReciboSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Recibos');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="recibo-index">
    <?php Pjax::begin(); echo GridView::widget([        
        'id' => 'grid-recibo',
        'resizableColumns'=>true,
        'persistResize'=>true,
        'responsive'=>true,
        'hover'=>true,
        'condensed'=>true,               
        'panel' => [
            'heading'=>'<h3 class="panel-title"><i class="glyphicon glyphicon-th-list"></i> '.Html::encode($this->title).' </h3>',
            'type'=>'info',
            'before'=>Html::a('<i class="glyphicon glyphicon-plus"></i> '.Yii::t('app', 'Create Recibo'), ['create'], ['class' => 'btn btn-success']).' '.
                      Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['index'], ['class' => 'btn btn-info']),
            'after' =>false,
        ],        
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
//            [   'class' => 'kartik\grid\SerialColumn'],
            [   'class' => '\kartik\grid\ExpandRowColumn',                
                'expandTitle'=>Yii::t('app','Expande'),
                'collapseTitle'=>Yii::t('app','Colapsa'),
                'collapseAllTitle' => Yii::t('app','Colapsa todos'),
                'expandAllTitle' => Yii::t('app','Expande todos'),                
                'expandIcon'=>'<span class="glyphicon glyphicon-plus-sign"></span>',
                'collapseIcon'=>'<span class="glyphicon glyphicon-minus-sign"></span>',
                'value' => function ($model, $key, $index, $column) {
                                return GridView::ROW_COLLAPSED;
                },
                'detailUrl' => Url::to(['recibopublicacao/index']),
                'detailRowCssClass' => GridView::TYPE_DANGER,
                'pageSummary' => false,
            ],
            'id',
            'nome',                           
            'data',
            ['class'=>  '\kartik\grid\DataColumn',
                'attribute'=>'valor',
                //'format'=>['decimal',2],
                'value' => function($model,$key,$index,$column) {
                    return Yii::$app->formatter->asCurrency($model->valor);
                },
                'hAlign'=>'right',
                ],            
            ['class' => '\kartik\grid\ActionColumn',
                'hiddenFromExport'=>true
            ],        
        ],
    ]); Pjax::end(); ?>

</div>

basic/views/recibo/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Recibo */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Recibo',
]) . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Recibos'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="recibo-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>