basic/models/Publicacao.php
<?php

namespace app\models;

use Yii;
use DateTime;

/**
 * This is the model class for table "publicacao".
 *
 * @property integer $id
 * @property string $tipoPublicacao
 * @property string $ISBN
 * @property string $titulo
 * @property string $subTitulo
 * @property string $dataEdicao
 * @property double $pVenda
 * @property integer $taxaIva
 * @property integer $idEditora
 *
 * @property DadosProducaoLivro $dadosProducao
 * @property EvolucaoVendas[] $evolucaoVendas
 * @property Editora $editora
 * @property PublicacaoAutor[] $autores
 * @property PublicacaoAutor[] $coordenadores
 * @property PublicacaoCustos[] $custos
 */
class Publicacao extends \yii\db\ActiveRecord
{
    private $c_descricao,$c_descricaoHTML;
    
    public function init() {
        $this->tipoPublicacao = "Livro";
        return parent::init();
    }
    
    
    /**
     * 
     * @param integer $id
     * @return \yii\db\Query
     */
    private static function findChartVendas($id) {
        $m = new \yii\db\Query;
        $m->select(['v.data','v.totalVendas','t.total','v.qtVendas','t.tiragem'])
            ->from(['v'=>'publicacaoautorvendas'])
            ->innerJoin(['t'=>'publicacaototais'],'t.id=v.idPublicacao')
            ->where(['v.idPublicacao'=>$id])
            ->orderBy('v.data');
        return $m;
    }
    
    /**
     * 
     * @return \yii\db\Query
     */
    public function getChart() {
        return Publicacao::findChartVendas($this->id);
    }
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'publicacao';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tipoPublicacao'], 'string'],
            [['tipoPublicacao','ISBN','titulo','dataEdicao', 'pVenda'], 'required'],
            [['ISBN'], 'unique'],
            [['dataEdicao'], 'safe'],
            [['pVenda'], 'number','min'=>0],
            [['taxaIva', 'idEditora'], 'integer'],
            [['ISBN'], 'string', 'max' => 13],
            [['titulo', 'subTitulo'], 'string', 'max' => 100],
            ['idEditora', 'exist','targetClass'=>'\app\models\Editora','targetAttribute'=>'id'],
            [['ISBN'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'tipoPublicacao' => Yii::t('app', 'Tipo Publicacao'),
            'ISBN' => Yii::t('app', 'Isbn'),
            'titulo' => Yii::t('app', 'Titulo'),
            'subTitulo' => Yii::t('app', 'Sub Titulo'),
            'dataEdicao' => Yii::t('app', 'Data Edicao'),
            'pVenda' => Yii::t('app', 'P Venda'),
            'taxaIva' => Yii::t('app', 'Taxa Iva'),
            'idEditora' => Yii::t('app', 'Id Editora'),
            'descricao' => Yii::t('app', 'Titulo'),
            'descricaoHTML' => Yii::t('app', 'Titulo'),            
        ];
    }

    /**
     * @return \yii\db\ActiveRecord
     */
    public function getDadosProducao()
    {
        return $this->hasOne(DadosProducaoLivro::className(), ['id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveRecord
     */
    public function getEvolucaoVendas()
    {
        return $this->hasMany(EvolucaoVendas::className(), ['ISBN' => 'ISBN']);
    }

    /**
     * @return \yii\db\ActiveRecord
     */
    public function getEditora()
    {
        return $this->hasOne(Editora::className(), ['id' => 'idEditora']);
    }

    /**
     * @return \yii\db\ActiveRecord
     */
    public function getAutores()
    {        
        return $this->hasMany(PublicacaoAutor::className(), ['idPublicacao' => 'id'])
                    ->andWhere(['tipoAutoria'=>'Autor']);

    }
    
    /**
     * @return \yii\db\ActiveRecord
     */
    public function getCoordenadores()
    {
        return $this->hasMany(PublicacaoAutor::className(), ['idPublicacao' => 'id'])
                    ->andWhere(['tipoAutoria'=>'Coordenador']);
    }

    /**
     * @return \yii\db\ActiveRecord
     */
    public function getCusto()
    {        
        return $this->hasMany(PublicacaoCusto::className(), ['idPublicacao' => 'id']);
    }
    
  
    public function beforeSave($insert) {        
        $this->dataEdicao=  \app\components\My::sqlData($this->dataEdicao);
        return parent::beforeSave($insert);
    }

    public function beforeValidate() {
        $a2=is_numeric("2014-02-03");
        $a=is_numeric($this->dataEdicao);
        $a1=intval($this->dataEdicao);
        if(is_numeric($this->dataEdicao) && intval($this->dataEdicao)>1930) {
            $this->dataEdicao = intval($this->dataEdicao).'-01-01';
        }

        $this->dataEdicao=  \app\components\My::sqlData($this->dataEdicao);
        return parent::beforeValidate();
    }
    public function afterValidate() {
        $this->dataEdicao=  \app\components\My::phpData($this->dataEdicao);
        return parent::afterValidate();
    }
    public function afterFind() {        
        $this->dataEdicao=  \app\components\My::phpData($this->dataEdicao);
        return parent::afterFind();
    }
    
    public function getDescricao($separador="\n") {
        if (isset($this->c_descricao))
            return $this->c_descricao;
        else
        return $this->titulo. ( $this->subTitulo!='' ? $separador .$this->subTitulo : '');
    }
        
    public function setDescricao( $descricao ) {
        $this->c_descricao = $descricao;
    }
    
    public function getDescricaoHTML() {
        if (isset($this->c_descricaoHTML))
            return $this->c_descricaoHTML;
        else
        return ( $this->titulo   !='' ? '<b>'.$this->titulo.'</b>':$this->titulo) . 
               ( $this->subTitulo!='' ? '<br>'.$this->subTitulo : '');
    }
        
    public function setDescricaoHTML( $descricao ) {
        $this->c_descricaoHTML = $descricao;
    }
    
    public function fixVal( $fieldName, $val ){
        
    }

}

basic/controllers/PublicacaoController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Publicacao;
use app\models\PublicacaoSearch;
use app\models\DadosProducaoLivro;
use app\components\MyController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\widgets\ActiveForm;
use app\components\MyExcel;
use yii\helpers\Json;

/**
 * PublicacaoController implements the CRUD actions for Publicacao model.
 */
class PublicacaoController extends MyController
{
    public $layout = 'main';    
    
    public $uploadFolder;
    
    public function init() {
        $this->uploadFolder = Yii::getAlias('@app') . "\upload_publicacoes\\";
        parent::init();
    }
        
    private function saveFile($model){
        if ($model->load(Yii::$app->request->post())){
            $file = \yii\web\UploadedFile::getInstance($model, 'ficheiro');              
            if($file!=null) {    
                $date = date_create($model->dataImportacao);
                $model->ficheiro='Publicacoes_'.date_format($date,"Y-m-d").'.'.$file->extension;                                
            }
            $path=$this->uploadFolder . $model->ficheiro;
            $file->saveAs($path,true);                                                                
            return true;            
        }
        return false;
    }    

    public function actionImport() {                 
        
        // retrieve selected ISBNs
        $p = Yii::$app->request->post();
        $ficheiro = $p['file'];
        $data = $p['date'];
        $selection = $p['selection'];
        foreach($selection as $i=>$v) {
            $selection[$i]= Json::decode($v);
            $selected[$selection[$i]['ISBN']] = true;
        }
        // retrieve data
        $storeVar = new \app\components\MyStoreVariable( $this->uploadFolder . basename($ficheiro).'.php' );        
        if(! $storeVar->exists()) {        
            return;
        }
        $arr = $storeVar->load();
        //
        $impModel = new \app\components\MyExcelImportModel('importacaoPublicacoes.json');
        
        $transaction = Yii::$app->db->beginTransaction();
        try {            
            $result=[];
            $i = 0;
            foreach ($arr as $v) {   
                if(! array_key_exists($v['ISBN'].'', $selected) || ! $v['_valid'])
                    continue;
                
                $reg1 = new Publicacao();
                $reg2 = new DadosProducaoLivro();                                    
                foreach ( $v as $fName => $fValue ) {
                    $fValue= $impModel->fixVal($fName, $fValue);                    
                    if    ( $reg1->hasAttribute( $fName ) )
                        $reg1->$fName = $fValue;
                    elseif( $reg2->hasAttribute( $fName ) )
                        $reg2->$fName = $fValue;
                                                            
                    if(strtolower($fName)=='editora'){
                        $reg1->idEditora = \app\models\Editora::insertIfNotExist($fValue);
                    }                    
                }
                                
                if( $reg1->validate() && $reg2->validate()) {                    
                    $reg1->save();                   
                    $reg2->id = $reg1->id;                    
                    $reg2->save();
                    
                    if(isset($v['autores'])){
                        $autores=  explode(";", $v['autores'].'');
                        foreach($autores as $autor) {
                            $nomes= explode(',',$autor);
                            $autorId = \app\models\Autor::insertIfNotExist( 
                                    trim($nomes[sizeof($nomes)-1]) ,
                                    sizeof($nomes)==3 ? trim($nomes[1]):'' ,
                                    sizeof($nomes)>1 ? trim($nomes[0]):'' 
                                    );
                            \app\models\PublicacaoAutor::insertIfNotExist( $reg1->id, $autorId, 'Autor');
                        }                    
                    }
                    
                    if(isset($v['vendas'])){
                        $ev = new \app\models\EvolucaoVendas();
                        $ev->ISBN       = $reg1->ISBN;
                        $ev->data       = strftime("%Y-%m-%d", strtotime("$reg1->dataEdicao +1 day"));
                        $ev->quantidade = $impModel->fixVal('vendas', $v['vendas']);
                        $ev->save();
                    }
                }else {
                    /*$err= [];
                    foreach(array_merge($reg1->errors,$reg2->errors) as $field=>$message){
                        $err['campo']=$field;
                        $err['_mensagem']=$message[0];
                    }                    */
                    $result[] = array_merge(
                                $reg1->toArray(),
                                ['_message'=>  \app\components\My::modelError2String(array_merge($reg1->errors,$reg2->errors))]
                        );
                }
            }            
            $transaction->commit();
            if($result==[]){
                $this->redirect('/publicacao');
            }else
                return $this->render('import', [
                    'file'        => $ficheiro,
                    'data'        => $data,
                    'result'      => $result,                                             
                    'columns'     => array_merge([
                            [   'class' => '\kartik\grid\ExpandRowColumn',                
                                'expandTitle'=>Yii::t('app','Expande'),
                                'collapseTitle'=>Yii::t('app','Colapsa'),
                                'collapseAllTitle' => Yii::t('app','Colapsa todos'),
                                'expandAllTitle' => Yii::t('app','Expande todos'),                
                                'expandIcon'=>'<span class="glyphicon glyphicon-plus-sign"></span>',
                                'collapseIcon'=>'<span class="glyphicon glyphicon-minus-sign"></span>',
                                'value' => function ($model, $key, $index, $column) {
                                               return $model['_message']=='' 
                                                       ? \kartik\grid\GridView::ROW_COLLAPSED
                                                       : \kartik\grid\GridView::ROW_EXPANDED;
                                },
                                'detail' => function ($model, $key, $index, $column) {
                                        return $model['_message'];
                                },                                    
                                'pageSummary' => false,
                            ],                                       
                        ], $impModel->columns),                                                                                 
                ]);
        } catch (Exception $e) {            
            $transaction->rollBack();
            throw EvolucaoVendasImportException($e->getMessage());
        }
        
    }
    
    /**
     * Importa relatorio mensal de vendas de Publicação.
     * @return mixed
     */
    public function actionUpload()
    {
        $model = new \app\models\PublicacaoImporta();
        
        if( $this->saveFile($model)) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return $this->redirect([
                    '/publicacao/confirmation',
                    'data'      => $model->dataImportacao,
                    'file'      => $model->ficheiro,
                    'random'    => $model->random]);
        } else
            return $this->render('upload', [
                'model'     => $model,             
            ]);
    }
    
    public function actionGetprogress($key) {
        $progressVar = new \app\components\MyStoreVariable();
        $progressVar->setFullPath($key.'.php');
        Yii::$app->response->format = Response::FORMAT_JSON;
        for($i=0;$i<10;$i++){
            if($progressVar->exists()) {
                $value = $progressVar->load();
                return ['progress'=>$value];
            }else
                sleep (0.025);
        }
    }
    
    public function actionConfirmation($data,$file,$random)
    {    
        $this->getView()->registerJsFile("/js/color.js");
        $path=$this->uploadFolder . $file;                          
  
        $impModel = new \app\components\MyExcelImportModel('importacaoPublicacoes.json');
        
        $storeVar = new \app\components\MyStoreVariable( $this->uploadFolder . basename($file).'.php' );        
//        $progressVar = new \app\components\MyStoreVariable();
//        $progressVar->setFullPath($random.'.php');
//        $progressBar=0;
//        $progressVar->save($progressBar);
        if(! $storeVar->exists()) {
            $ex = new MyExcel();
            $ex->readSpreadsheetData($path);        
//            $progressBar+=5;$progressVar->save($progressBar);            
            $arr=$ex->export2Array( $impModel );
//            $i=0;
            foreach($arr as $recno=>$record){
//                $i++;
//                $progressBar= 5 + ( $i/sizeof($arr)*95 ); $progressVar->save($progressBar);
                $arr[$recno]['_valid'] = true;
                if( $arr[$recno]['_valid'] ) {
                    $m1 = new Publicacao();
                    $m2 = new DadosProducaoLivro();                    
                    foreach ( $record as $fName => $fValue ) {
                    //    sleep(20);
                        $fValue= $impModel->fixVal($fName, $fValue);                        
                        if    ( $m1->hasAttribute( $fName ) )
                            $m1->$fName = $fValue;

basic/views/publicacao/_chart.php
<?php

use yii\helpers\Html;
use app\components\My;
use fruppel\googlecharts\GoogleCharts;


/* @var $this yii\web\View */
/* @var $model app\models\Publicacao */

$arr = $model->chart->all(); //'v.data','v.totalVendas','t.total'])
$data= [['Mes', 'Vendas',['type' => 'string', 'role' => 'tooltip']]];
if(count($arr)==0 && ! isset($model->dadosProducao) ){
    echo 'não existem vendas';
    return;
}
$maxVendas=isset($model->dadosProducao) ? $model->dadosProducao->tiragem * $model->pVenda : 0;
$totalVendas=0;    
$tiragem=0;
$qtVendas=0;
foreach($arr as  $k=>$v){
    $tiragem=doubleval($v['tiragem']);
    $qtVendas=doubleval($v['qtVendas']);
    $maxVendas=doubleval($v['total']);
    $totalVendas=doubleval($v['totalVendas']);
    $d= explode('-', My::sqlData($v['data']));
    $mes= new yii\web\JsExpression( "new Date($d[0],$d[1],$d[2])");
    $toolTip = Yii::$app->formatter->asDate($v['data'],'php:d-m-Y')." \n";
    $perc = Yii::$app->formatter->asDecimal($totalVendas/$maxVendas*100,1). '%';
    $toolTip.= Yii::$app->formatter->asCurrency($v['totalVendas'])."\n $perc do total vendas";
    $data[] = [$mes,  $totalVendas,$toolTip];
}
$maxVendas = $totalVendas!=0 ? $totalVendas : $maxVendas;?>
<div class="chartPubAreabar" style="width:58%;height:98%;display:inline-block">
<?= GoogleCharts::widget([
        'id' => 'AreaChart'.$model->ISBN,
        'visualization' => 'AreaChart',
        'responsive'   => true,
        'options' => [            
            'title'         => 'Vendas '.$model->getDescricao(' - '),
            'pointsVisible' => true,
            'tooltip'       => [ 'isHtml'      => true ],
            'hAxis'         => [
                'title'             => 'Mes',
                'format'            => 'MMM, y',
                'titleTextStyle'    => ['color' => '#333'],
            ],
            'vAxis'         => [
                'format'    => 'currency',  
                'minValue'  => 0,
                'maxValue'  => 500,
                'ticks'     => [ 0, floor($maxVendas/4*1) ,floor($maxVendas/2), floor($maxVendas/4*3),$maxVendas],
                'gridlines' => [ 'count'    => 3 ],
            ],            
        ],
        'dataArray' =>  $data 
    ]);
?>
</div>
<div class="charPubPie" style="width:40%;height:98%;display:inline-block">
<?php echo GoogleCharts::widget([
	'id' => 'PieChart'.$model->ISBN,
	'visualization' => 'PieChart',
        'options' => [
            'title' => '',
            'is3D' => true,
        ],
        'responsive' => true,
	'data' => [
            'cols' => [
                [
                    'id' => 'topping',
                    'label' => 'Topping',
                    'type' => 'string'
                ],
                [
                    'id' => 'slices',
                    'label' => 'Slices',
                    'type' => 'number'
                ]
            ],
            'rows' => [
                            [
                                'c' => [
                                    ['v' => 'Vendidos'],
                                    ['v' => $qtVendas]
                                ],
                            ],
                            [
                                'c' => [
                                    ['v' => 'Por Vender'],
                                    ['v' => $tiragem-$qtVendas]
                                ]
                            ],                
                    ]
        ],
    
]); ?>
</div>

basic/views/publicacao/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\web\JsExpression;
use yii\jui\Tabs;

/* @var $this yii\web\View */
/* @var $model app\models\Publicacao */
/* @var $form yii\widgets\ActiveForm */

?>
    <?= Tabs::widget([
        'options' => ['tag' => 'div'],
        'itemOptions' => ['tag' => 'div'],
        'headerOptions' => ['class' => 'panelLink'],
        'clientOptions' => ['collapsible' => false],
        'items' => [
            [   'label'     =>'Publicação',
                'content'   =>$this->render('_form_publicacao',['model'=>$model]),
                'options'   => ['id' => 'tab-publicacao', 
                             /*   'data-url'  =>yii\helpers\Url::toRoute(
                                        (isset($model->isNewRecord)
                                            ?  ['publicacao/create']
                                            :  ['publicacao/insert', 'id' => $model->id])), */
                                ],                
                ],
            [   'label'     =>'Dados produção',
                'content'   =>'',                                
                'options'   => ['id' => 'tab-dadosproducao',
                                'data-url'  =>yii\helpers\Url::toRoute(
                                        ['dadosproducaolivro/update', 'id' => $model->id]), 
                                ],                
                ],
            [   'label'     =>'Autores',
                'content'   =>'',                

                'options'   => ['id' => 'tab-autores',
                                'data-url'  =>yii\helpers\Url::toRoute(
                                        ['publicacaoautor/index', 'idPublicacao' => $model->id, 'tipoAutoria'=> 'Autor']),
                                ]                
                ],
            [   'label'     =>'Coordenadores',
                'content'   =>'',
                'options'   => ['id' => 'tab-coordenadores',
                                'data-url'  =>yii\helpers\Url::toRoute(
                                        ['publicacaoautor/index', 'idPublicacao' => $model->id, 'tipoAutoria'=> 'Coordenador']),
                            ],                
                ],
            [   'label'     =>'Custos',
                'content'   =>'',
                'options'   => ['id' => 'tab-custos',
                                'data-url'  =>yii\helpers\Url::toRoute(
                                        ['publicacaocusto/index', 'id' => $model->id]),
                            ],                
                ],
        ],                
        'clientEvents' => [                                                         
            'beforeActivate' => new JsExpression("function( event, ui ){                
                var url=ui.newPanel.data('url') == undefined ? '' : ui.newPanel.data('url');       
                var loaded=ui.newPanel.data('loaded') == undefined ? '' : ui.newPanel.data('loaded');                      
                if(loaded=='')
                    loadIntoPanel(ui.newPanel,url,'GET',true)
                else
                    addHistory(ui.newPanel,loaded);
            }"),
        ]
        
    ]);?>  

<?php
$disableTabs = !$model->isNewRecord ? ""
                    : "$('.ui-tabs').tabs( 'option', 'disabled',[1,2,3,4]);" ;
$script = <<<EOD
$disableTabs        

EOD;
$this->registerJs($disableTabs);
?>

basic/views/publicacao/_form_publicacao.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\web\JsExpression;

/* @var $this yii\web\View */
/* @var $model app\models\Publicacao */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="publicacao-form">

    <?php $form = ActiveForm::begin([
        'enableClientScript' => true,
        'enableClientValidation' => true,
        'enableAjaxValidation' => true,
        'validateOnSubmit'=>true,
                ]); ?>
 

    <?= $form->field($model, 'tipoPublicacao')
                    ->dropDownList([ 'Livro' => 'Livro', 'Outro' => 'Outro', ], 
                    array_merge(['prompt'   => ''], 
                        $model->isNewRecord ? [] : ['disabled'=>'true']  ))  ?>

    <?= $form->field($model, 'ISBN')->textInput(['maxlength' => 13]) ?>

    <?= $form->field($model, 'titulo')->textInput(['maxlength' => 50]) ?>

    <?= $form->field($model, 'subTitulo')->textInput(['maxlength' => 50]) ?>

    <?= $form->field($model, 'dataEdicao')->widget(\yii\jui\DatePicker::classname(), [
        'options'       => ['class' => 'form-control'],
        'language' => 'pt',
        'dateFormat' => 'dd-MM-yyyy',        
    ]) ?>

    <?= $form->field($model, 'pVenda')->widget(kartik\money\MaskMoney::classname(), [
                'pluginOptions' => [
                    'prefix' => '€ ',
                    'suffix' => '',
                    'allowNegative' => false
                ]
            ]);
    ?>
    <?= $form->field($model, 'taxaIva')->textInput() ?>
    
    <?php $acUrl = Url::to('editora/autocomplete',true); ?>
    
    <?= $form->field($model, 'idEditora')->widget(\app\components\MyAutoComplete::classname(), 
        [   'ajaxUrl'       => $acUrl ,
            'options'       => ['class' => 'form-control'],            
            'clientOptions' => [
                'name'  => 'Publicacao[idEditora]',
                'value' => $model->idEditora,
                ]
            ]) ?>
    
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

basic/views/publicacao/_form_upload.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;


/* @var $this yii\web\View */
/* @var $model app\models\EvolucaoVendasImporta */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="publicacao-upload-form">

    <?php $form = ActiveForm::begin([
        'id' => 'PublicacaoImporta',
        'options' => ['enctype' => 'multipart/form-data'],
        'validationUrl' => ['/publicacao/validate'],
        'method'=>'post',
    ]); ?>
    <?= $form->field($model, 'dataImportacao',['options'=>["style"=>"display:none"]])->hiddenInput() ?>
    <?= $form->field($model, 'random',['options'=>["style"=>"display:none"]])->hiddenInput() ?>
    <?= $form->field($model, 'ficheiro')->fileInput(['maxlength' => 255]) ?>   

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Importa'), ['btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
    <div id="ajaxWait" style="display:none;">
        <div id="bodyCover"></div>
        <img src="/img/ajax loader.gif">
    </div>
</div>

<?php
$script = <<<EOD
$("form").submit( function(event) {        
        $("#ajaxWait").show("slow");
});    
EOD;
$this->registerJs($script);        
?>

basic/views/publicacao/import_confirmation.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\data\ArrayDataProvider;
use yii\helpers\BaseInflector;

/* @var $this yii\web\View */
/* @var $array array */
/* @var $columns array */
/* @var $file string */
/* @var $data string */


$this->title = Yii::t('app', 'Confirmação Publicações');
$this->params['breadcrumbs'][] = $this->title;

$importUrl = yii\helpers\Url::to(['/publicacao/import',[''=>'',''=>'']]);
$saveImportUrl = yii\helpers\Url::to(['/publicacao/saveimport',[''=>'',''=>'']]);
?>
<div class="evolucao-vendas-index">

    <h1><?= Html::encode($this->title) ?></h1>    
           
    <?=Html::beginForm($importUrl,'post');?>
        <p>
    <?=Html::submitInput( Yii::t('app', 'Importa {ficheiro}',['ficheiro'=>  BaseInflector::titleize($file)]), ['class' => 'btn btn-success']) ?>            
        </p>
    <?=Html::hiddenInput('file', $file);?>
    <?=Html::hiddenInput('date', $data);?>
    <?php
        $cols = array_merge([['class' => 'yii\grid\SerialColumn']],$columns );
        echo GridView::widget([
                    'dataProvider' => new ArrayDataProvider([
                                                'allModels' => $array,    
                                                'pagination' => [
                                                    'pageSize' => 9999,
                                                ]
                                    ]),        
                    'resizableColumns'=>true,    
                    'persistResize'=>true,
                    'rowOptions'   => function ($model, $index, $widget, $grid) {
                                        return ['class'=>'importRecno'];
                        },

                    'columns' => $cols,

                ]); 
        echo Html::endForm();
        ?>            
    <div id="ajaxWait" style="display:none;">
        <div id="bodyCover"></div>
        <img src="/img/ajax loader.gif">
    </div>
</div>

<?php
$script = <<<EOD
$("form").submit( function(event) {        
        $("#ajaxWait").show("slow");
});            
$.each($('.importRecno').find('input[type=checkbox][disabled]').closest('.importRecno').find('td'),function( idx, me ){
        var bgCor = getBgColorHex($(me).css("color"));
        var newBgCor=LightenDarkenColor(bgCor, 60);
        $(me).css("color",newBgCor);        
});

$("input[type=submit]").attr("disabled", $('input[name="selection[]"]:not(:disabled)').length==0 ? "" : undefined );   
EOD;
$this->registerJs($script);

$script = <<<EOD
$("input[type=checkbox]").change( function() {
    var form = $(this).closest("form");
    var postData = $(form).serialize();                        
    $.ajax({
        url: '$saveImportUrl',
        type: (form.attr('method')!=''?form.attr('method'):'post').toUpperCase(),
        data: postData,        
        contentType: ($(this).find('input[type=file]').length>0 ? false : 'application/x-www-form-urlencoded; charset=UTF-8'),
        cache: false,
        processData:false,
        complete:function(jqXHR, textStatus ){
            var a = this;
        },
        success: function (data, textStatus, jqXHR ){
            var a = this;
        },
        error: function (jqXHR, textStatus, errorThrown) {
            var a = this;
        }
    });
});
EOD;
//$this->registerJs($script);
?>